api = "0.7"

[buildpack]
  description = "A buildpack for running a default rake task for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/rake"
  id = "paketo-buildpacks/rake"
  keywords = ["ruby", "rake"]
  name = "Paketo Buildpack for Rake"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/rake/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
