api = "0.2"

[buildpack]
  id = "paketo-buildpacks/rake"
  name = "Paketo Rake Buildpack"
  homepage = "https://github.com/paketo-buildpacks/rake"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/run", "bin/build","bin/detect","buildpack.toml"]
  pre_package = "./scripts/build.sh"
